# Generated by Django 5.0.2 on 2024-04-15 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('modalidade', models.CharField(max_length=20)),
                ('relevancia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=1000)),
                ('descricao', models.TextField(max_length=1000)),
                ('cadastrado', models.BooleanField(default=False)),
                ('ref_ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_trenzinho.ranking')),
            ],
        ),
    ]
